/**
 * Static GP circuit metadata — history, typical conditions, strategy info.
 * Provides contextual information when a Grand Prix is loaded.
 */

export interface CircuitInfo {
  name: string;
  country: string;
  city: string;
  length_km: number;
  laps: number;
  turns: number;
  drs_zones: number;
  first_gp: number;
  lap_record: { time: string; driver: string; year: number };
  typical_weather: string;
  track_type: string;
  overtaking: "Low" | "Medium" | "High";
  tyre_wear: "Low" | "Medium" | "High";
  typical_strategy: string;
  key_facts: string[];
}

export const CIRCUIT_DATABASE: Record<string, CircuitInfo> = {
  bahrain: {
    name: "Bahrain International Circuit",
    country: "Bahrain",
    city: "Sakhir",
    length_km: 5.412,
    laps: 57,
    turns: 15,
    drs_zones: 3,
    first_gp: 2004,
    lap_record: { time: "1:31.447", driver: "Pedro de la Rosa", year: 2005 },
    typical_weather: "Hot & dry, 30-35°C air, 40-50°C track. Night race with cooler temps in later stints.",
    track_type: "Purpose-built desert circuit with long straights and heavy braking zones",
    overtaking: "High",
    tyre_wear: "High",
    typical_strategy: "1-stop (M→H) or 2-stop (S→H→M). High degradation makes 2-stop viable.",
    key_facts: [
      "Night race under floodlights since 2014",
      "Turn 1-4 complex is key overtaking zone",
      "3 DRS zones create multiple passing opportunities",
      "Rear-limited circuit — high tyre degradation",
    ],
  },
  jeddah: {
    name: "Jeddah Corniche Circuit",
    country: "Saudi Arabia",
    city: "Jeddah",
    length_km: 6.174,
    laps: 50,
    turns: 27,
    drs_zones: 3,
    first_gp: 2021,
    lap_record: { time: "1:30.734", driver: "Lewis Hamilton", year: 2021 },
    typical_weather: "Hot & humid, 28-32°C. Night race.",
    track_type: "Ultra-fast street circuit — second-fastest on calendar",
    overtaking: "Medium",
    tyre_wear: "Low",
    typical_strategy: "1-stop (M→H or S→H). Low degradation favors one stop.",
    key_facts: [
      "Fastest street circuit in F1 history",
      "Average speed over 250 km/h",
      "Blind corners at high speed demand confidence",
      "Safety cars common — strategic wildcard",
    ],
  },
  australia: {
    name: "Albert Park Circuit",
    country: "Australia",
    city: "Melbourne",
    length_km: 5.278,
    laps: 58,
    turns: 14,
    drs_zones: 4,
    first_gp: 1996,
    lap_record: { time: "1:19.813", driver: "Charles Leclerc", year: 2024 },
    typical_weather: "Variable — 18-25°C. Can change rapidly. Rain possible.",
    track_type: "Semi-permanent street circuit through parkland",
    overtaking: "High",
    tyre_wear: "Medium",
    typical_strategy: "1-stop (H→M) or 2-stop. Safety cars are frequent — flexibility is key.",
    key_facts: [
      "4 DRS zones after 2022 redesign",
      "Historically high safety car rate",
      "Turn 11-12 chicane removed for 2022, increasing speed",
      "Season opener atmosphere — huge crowds",
    ],
  },
  monaco: {
    name: "Circuit de Monaco",
    country: "Monaco",
    city: "Monte Carlo",
    length_km: 3.337,
    laps: 78,
    turns: 19,
    drs_zones: 1,
    first_gp: 1950,
    lap_record: { time: "1:12.909", driver: "Lewis Hamilton", year: 2021 },
    typical_weather: "Mediterranean — 20-25°C. Occasional rain creates chaos.",
    track_type: "Iconic tight street circuit — the ultimate driver test",
    overtaking: "Low",
    tyre_wear: "Low",
    typical_strategy: "1-stop mandatory. Qualifying is everything — track position wins races.",
    key_facts: [
      "Most prestigious race on the F1 calendar",
      "Overtaking nearly impossible — qualifying is crucial",
      "The tunnel creates unique light/dark transition",
      "Swimming pool chicane is one of F1's iconic corners",
    ],
  },
  silverstone: {
    name: "Silverstone Circuit",
    country: "United Kingdom",
    city: "Silverstone",
    length_km: 5.891,
    laps: 52,
    turns: 18,
    drs_zones: 2,
    first_gp: 1950,
    lap_record: { time: "1:27.097", driver: "Max Verstappen", year: 2020 },
    typical_weather: "Unpredictable British weather — 15-22°C. Rain always possible.",
    track_type: "High-speed flowing circuit — tests aerodynamic efficiency",
    overtaking: "Medium",
    tyre_wear: "High",
    typical_strategy: "2-stop common due to high-speed corners causing front-left degradation.",
    key_facts: [
      "Home of British motorsport since 1950",
      "Copse, Maggots, Becketts — legendary high-speed sequence",
      "Front-left tyre critical due to high-speed right-handers",
      "Biggest crowd attendance of any F1 race",
    ],
  },
  monza: {
    name: "Autodromo Nazionale Monza",
    country: "Italy",
    city: "Monza",
    length_km: 5.793,
    laps: 53,
    turns: 11,
    drs_zones: 2,
    first_gp: 1950,
    lap_record: { time: "1:21.046", driver: "Rubens Barrichello", year: 2004 },
    typical_weather: "Warm — 25-30°C. Late summer Italian heat.",
    track_type: "Temple of Speed — lowest downforce, highest top speeds",
    overtaking: "High",
    tyre_wear: "Low",
    typical_strategy: "1-stop (M→H). Low-downforce setup means less tyre stress.",
    key_facts: [
      "Fastest circuit on the F1 calendar",
      "The Tifosi create an electric atmosphere",
      "Slipstreaming and DRS make overtaking frequent",
      "Cars run minimum downforce — top speeds over 340 km/h",
    ],
  },
  spa: {
    name: "Circuit de Spa-Francorchamps",
    country: "Belgium",
    city: "Spa",
    length_km: 7.004,
    laps: 44,
    turns: 19,
    drs_zones: 2,
    first_gp: 1950,
    lap_record: { time: "1:46.286", driver: "Valtteri Bottas", year: 2018 },
    typical_weather: "Highly variable — the Ardennes microclimate. Rain can affect one sector but not another.",
    track_type: "Classic high-speed circuit through Ardennes forest",
    overtaking: "High",
    tyre_wear: "Medium",
    typical_strategy: "1-stop (S→M or M→H). Eau Rouge/Raidillon and long Kemmel straight create natural passing zones.",
    key_facts: [
      "Longest circuit on the calendar at 7km",
      "Eau Rouge / Raidillon — F1's most famous corner complex",
      "Microclimates mean it can be raining in one sector and dry elsewhere",
      "One of the best circuits for on-track racing",
    ],
  },
  singapore: {
    name: "Marina Bay Street Circuit",
    country: "Singapore",
    city: "Singapore",
    length_km: 4.940,
    laps: 62,
    turns: 19,
    drs_zones: 3,
    first_gp: 2008,
    lap_record: { time: "1:35.867", driver: "Lewis Hamilton", year: 2023 },
    typical_weather: "Hot and extremely humid — 30°C+, 80%+ humidity. Night race.",
    track_type: "Demanding street circuit — most physically challenging race",
    overtaking: "Low",
    tyre_wear: "Medium",
    typical_strategy: "1-stop or 2-stop. Safety cars very likely — pit window flexibility critical.",
    key_facts: [
      "Most physically demanding race — nearly 2 hours",
      "First ever F1 night race",
      "Very high safety car probability",
      "Humidity and heat make driver fitness crucial",
    ],
  },
  suzuka: {
    name: "Suzuka International Racing Course",
    country: "Japan",
    city: "Suzuka",
    length_km: 5.807,
    laps: 53,
    turns: 18,
    drs_zones: 2,
    first_gp: 1987,
    lap_record: { time: "1:30.983", driver: "Lewis Hamilton", year: 2019 },
    typical_weather: "Variable — 20-25°C. Typhoon season can bring interruptions.",
    track_type: "Figure-8 layout with legendary fast corners",
    overtaking: "Medium",
    tyre_wear: "High",
    typical_strategy: "1-stop or 2-stop. High-speed corners cause significant tyre wear.",
    key_facts: [
      "Only figure-8 circuit in F1 (track crosses under itself)",
      "130R — one of the fastest corners in F1",
      "S Curves demand perfect car balance",
      "Japanese fans are among the most passionate in F1",
    ],
  },
  // Catch-all alias mappings
  "saudi arabia": {
    name: "Jeddah Corniche Circuit", country: "Saudi Arabia", city: "Jeddah",
    length_km: 6.174, laps: 50, turns: 27, drs_zones: 3, first_gp: 2021,
    lap_record: { time: "1:30.734", driver: "Lewis Hamilton", year: 2021 },
    typical_weather: "Hot & humid, 28-32°C. Night race.",
    track_type: "Ultra-fast street circuit",
    overtaking: "Medium", tyre_wear: "Low",
    typical_strategy: "1-stop (M→H or S→H).",
    key_facts: ["Fastest street circuit in F1 history", "Average speed over 250 km/h"],
  },
  "great britain": {
    name: "Silverstone Circuit", country: "United Kingdom", city: "Silverstone",
    length_km: 5.891, laps: 52, turns: 18, drs_zones: 2, first_gp: 1950,
    lap_record: { time: "1:27.097", driver: "Max Verstappen", year: 2020 },
    typical_weather: "Unpredictable British weather — 15-22°C.",
    track_type: "High-speed flowing circuit",
    overtaking: "Medium", tyre_wear: "High",
    typical_strategy: "2-stop common due to high degradation.",
    key_facts: ["Home of British motorsport", "Copse-Maggots-Becketts legendary sequence"],
  },
  austria: {
    name: "Red Bull Ring",
    country: "Austria",
    city: "Spielberg",
    length_km: 4.318,
    laps: 71,
    turns: 10,
    drs_zones: 3,
    first_gp: 1970,
    lap_record: { time: "1:05.619", driver: "Carlos Sainz", year: 2020 },
    typical_weather: "Alpine weather — 20-28°C. Can change quickly with mountain storms.",
    track_type: "Short, high-altitude circuit with elevation changes",
    overtaking: "High",
    tyre_wear: "Medium",
    typical_strategy: "1-stop (S→H or M→H). Short lap means frequency of pit opportunities.",
    key_facts: [
      "Shortest lap on calendar — just over a minute",
      "3 DRS zones create excellent overtaking",
      "High altitude affects engine performance",
      "Stunning Styrian mountain backdrop",
    ],
  },
  hungary: {
    name: "Hungaroring",
    country: "Hungary",
    city: "Budapest",
    length_km: 4.381,
    laps: 70,
    turns: 14,
    drs_zones: 2,
    first_gp: 1986,
    lap_record: { time: "1:16.627", driver: "Lewis Hamilton", year: 2020 },
    typical_weather: "Hot — 30-35°C. Summer heat in Budapest.",
    track_type: "Twisty, Monaco-like circuit without walls",
    overtaking: "Low",
    tyre_wear: "High",
    typical_strategy: "2-stop often optimal due to high degradation. Alternative strategies can work.",
    key_facts: [
      "Called 'Monaco without the walls'",
      "Very difficult to overtake — qualifying critical",
      "High tyre degradation opens strategic windows",
      "Turn 4 hairpin is primary overtaking spot",
    ],
  },
  italy: {
    name: "Autodromo Nazionale Monza", country: "Italy", city: "Monza",
    length_km: 5.793, laps: 53, turns: 11, drs_zones: 2, first_gp: 1950,
    lap_record: { time: "1:21.046", driver: "Rubens Barrichello", year: 2004 },
    typical_weather: "Warm — 25-30°C.",
    track_type: "Temple of Speed",
    overtaking: "High", tyre_wear: "Low",
    typical_strategy: "1-stop (M→H).",
    key_facts: ["Fastest circuit in F1", "Top speeds over 340 km/h"],
  },
  belgium: {
    name: "Circuit de Spa-Francorchamps", country: "Belgium", city: "Spa",
    length_km: 7.004, laps: 44, turns: 19, drs_zones: 2, first_gp: 1950,
    lap_record: { time: "1:46.286", driver: "Valtteri Bottas", year: 2018 },
    typical_weather: "Highly variable Ardennes weather.",
    track_type: "Classic high-speed circuit",
    overtaking: "High", tyre_wear: "Medium",
    typical_strategy: "1-stop (S→M or M→H).",
    key_facts: ["Longest circuit at 7km", "Eau Rouge / Raidillon iconic complex"],
  },
  japan: {
    name: "Suzuka International Racing Course", country: "Japan", city: "Suzuka",
    length_km: 5.807, laps: 53, turns: 18, drs_zones: 2, first_gp: 1987,
    lap_record: { time: "1:30.983", driver: "Lewis Hamilton", year: 2019 },
    typical_weather: "Variable — typhoon season.",
    track_type: "Figure-8 layout with legendary corners",
    overtaking: "Medium", tyre_wear: "High",
    typical_strategy: "1-stop or 2-stop.",
    key_facts: ["Only figure-8 circuit", "130R is one of the fastest corners"],
  },
  china: {
    name: "Shanghai International Circuit",
    country: "China",
    city: "Shanghai",
    length_km: 5.451,
    laps: 56,
    turns: 16,
    drs_zones: 2,
    first_gp: 2004,
    lap_record: { time: "1:32.238", driver: "Michael Schumacher", year: 2004 },
    typical_weather: "Variable — 15-25°C. Can be wet in April.",
    track_type: "Modern Tilke circuit with unique long back straight",
    overtaking: "High",
    tyre_wear: "Medium",
    typical_strategy: "1-stop or 2-stop. Long back straight enables DRS passes.",
    key_facts: [
      "1.2km back straight — longest on calendar",
      "Turn 1-2-3 complex inspired by the Chinese character 'shang'",
      "Returned to calendar in 2024 after 4-year absence",
    ],
  },
  spain: {
    name: "Circuit de Barcelona-Catalunya",
    country: "Spain",
    city: "Barcelona",
    length_km: 4.657,
    laps: 66,
    turns: 16,
    drs_zones: 2,
    first_gp: 1991,
    lap_record: { time: "1:18.149", driver: "Max Verstappen", year: 2023 },
    typical_weather: "Warm & dry — 25-30°C. Consistent conditions.",
    track_type: "Technical all-rounder — traditional pre-season test venue",
    overtaking: "Medium",
    tyre_wear: "High",
    typical_strategy: "2-stop common. High energy through Turn 3 causes significant wear.",
    key_facts: [
      "The ultimate all-round test for car and driver",
      "Turn 3 right-hander is hardest on tyres",
      "Used extensively for pre-season testing",
    ],
  },
  miami: {
    name: "Miami International Autodrome",
    country: "USA",
    city: "Miami Gardens",
    length_km: 5.412,
    laps: 57,
    turns: 19,
    drs_zones: 3,
    first_gp: 2022,
    lap_record: { time: "1:29.708", driver: "Max Verstappen", year: 2023 },
    typical_weather: "Hot & humid, 30-35°C. Tropical — rain possible in late afternoon.",
    track_type: "Street circuit around Hard Rock Stadium with long straights and tight chicanes",
    overtaking: "Medium",
    tyre_wear: "Medium",
    typical_strategy: "1-stop (M→H or S→M). High track temps increase degradation. Safety cars possible.",
    key_facts: [
      "Built around Hard Rock Stadium — home of the Miami Dolphins",
      "Features a fake marina with yachts and water inside the circuit",
      "3 DRS zones provide strong overtaking opportunities",
      "Lap 1 Turn 1 is a key overtaking zone with heavy braking",
      "Norris won the first non-Red Bull race here in 2024",
    ],
  },
  canada: {
    name: "Circuit Gilles Villeneuve",
    country: "Canada",
    city: "Montreal",
    length_km: 4.361,
    laps: 70,
    turns: 14,
    drs_zones: 2,
    first_gp: 1978,
    lap_record: { time: "1:13.078", driver: "Valtteri Bottas", year: 2019 },
    typical_weather: "Variable — 18-25°C. Rain possible. Island microclimate.",
    track_type: "Semi-permanent circuit on Ile Notre-Dame",
    overtaking: "High",
    tyre_wear: "Low",
    typical_strategy: "1-stop typical. Safety cars frequent — reactive strategy helps.",
    key_facts: [
      "Wall of Champions at final chicane has caught many greats",
      "Set on an island in the St. Lawrence River",
      "High safety car rate creates strategic opportunities",
      "Hard braking zones stress brakes heavily",
    ],
  },
  "abu dhabi": {
    name: "Yas Marina Circuit",
    country: "UAE",
    city: "Abu Dhabi",
    length_km: 5.281,
    laps: 58,
    turns: 16,
    drs_zones: 2,
    first_gp: 2009,
    lap_record: { time: "1:26.103", driver: "Max Verstappen", year: 2021 },
    typical_weather: "Hot and dry — 28-32°C. Twilight race — starts in daylight, ends under lights.",
    track_type: "Modern facility — season finale venue",
    overtaking: "Medium",
    tyre_wear: "Medium",
    typical_strategy: "1-stop (M→H or S→M). Track evolved in 2021 redesign for better racing.",
    key_facts: [
      "Season finale venue since 2009",
      "Twilight race — day to night transition",
      "2021 redesign removed chicanes for better overtaking",
      "Iconic pit building cars drive through",
    ],
  },
};

/**
 * Resolve circuit info from a GP name/circuit string.
 * Tries exact match, then lowercase, then partial matching.
 */
export function getCircuitInfo(gpName: string): CircuitInfo | null {
  const key = gpName.toLowerCase().trim();
  if (CIRCUIT_DATABASE[key]) return CIRCUIT_DATABASE[key];

  // Try partial match
  for (const [k, v] of Object.entries(CIRCUIT_DATABASE)) {
    if (key.includes(k) || k.includes(key)) return v;
  }

  // Try matching on name/country/city
  for (const v of Object.values(CIRCUIT_DATABASE)) {
    const searchable = `${v.name} ${v.country} ${v.city}`.toLowerCase();
    if (searchable.includes(key) || key.includes(v.country.toLowerCase())) return v;
  }

  return null;
}
